<?php 
    require_once('conexion/conexion.php');
    include_once 'includes/header.php'; 

    $query = "SELECT Empleados.ficha_empleado, Nombre_empleados.nombre, Empleados.cedula , Empleados.codigo_unidad 
    FROM Empleados,Nombre_empleados 
    WHERE Empleados.cedula = Nombre_empleados.cedula;";
    $result = pg_query($db_connection, $query);
    $count_result = pg_query($db_connection, $query);

?>

<html>
    <head>
        <style type="text/css">
            @keyframes ldio-q0sn9pt0muq {
            0% { transform: translate(-50%,-50%) rotate(0deg); }
            100% { transform: translate(-50%,-50%) rotate(360deg); }
            }
            .ldio-q0sn9pt0muq div {
            position: absolute;
            width: 30.99px;
            height: 30.99px;
            border: 5.91px solid #3be8b0;
            border-top-color: transparent;
            border-radius: 50%;
            }
            .ldio-q0sn9pt0muq div {
            animation: ldio-q0sn9pt0muq 1s linear infinite;
            top: 48.5px;
            left: 48.5px
            }
            .loadingio-spinner-rolling-bqrptym85uo {
            width: 100px;
            height: 100px;
            display: inline-block;
            overflow: hidden;
            background: rgba(241, 242, 243, 0);
            }
            .ldio-q0sn9pt0muq {
            width: 20%;
            height: 20%;
            position: relative;
            transform: translateZ(0) scale(1);
            backface-visibility: hidden;
            transform-origin: 0 0; /* see note above */
            }
            .ldio-q0sn9pt0muq div { box-sizing: content-box; }
            /* generated by https://loading.io/ */
        </style>
        <title>Empleados</title>
        <link rel='shortcut icon' href='favicon.ico' type='image/x-icon' />
    </head>
    <body>
        <div class="mx-auto mt-4 mb-4" style="width: 220px;">
            <span class="titulo">Empleados <i class="align-middle material-icons"> person</i></span>
        </div>
        <div class="add-sede rounded-lg shadow bg-light pb-2 pt-2 ml-3 mr-3">
            <div class="mx-auto mt-2 mb-4 text-center">
                <span class="subtitulo">Añadir Empleado</span>
            </div>

            <form class="needs-validation ml-5 mr-5" id="add_empleado" action="add-empleado.php" method="post" novalidate>
                <div class="form-row">
                <div class="col-md-4 mb-3">
                        <label for="validationTooltip01">Unidad a la que pertenece</label>
                        <select id="select-unidad" class="form-control">
                            <option value="NULL" disabled selected>Seleccionar una unidad</option>
                            <?
                                $listar_unidades = "SELECT codigo_unidad, nombre FROM Unidades;";
                                $result_search = pg_query($db_connection, $listar_unidades);
                                while($row = pg_fetch_row($result_search)){
                            ?>
                                <option value="<?echo $row[0];?>"><?echo $row[1];?></option>
                            <?}?>
                        </select>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label for="validationTooltip02">Cedula</label>
                        <input type="text" name="descripcion" class="form-control" id="cedula" placeholder="Cedula" required>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label for="validationTooltip03">Nombre</label>
                        <input type="text" name="nombre" class="form-control" id="nombre" placeholder="Nombre" required>
                    </div>
                </div>
                <div class="mx-auto text-center">
                    <button class="btn btn-success" id="add_empleado_btn" type="button">Añadir</button>
                </div>
            </form>
            <div class="subtitulo mx-auto rounded bg-success round text-light text-center d-none"  id="add-empleado-success">
                <span class="mx-auto">Empleado añadido correctamente</span>
            </div>
            <div class="subtitulo mx-auto rounded bg-danger round text-light text-center d-none"  id="add-empleado-error">
                <span class="mx-auto">El empleado no pudo ser añadido, revise los datos</span>
            </div>
        </div>

        <?if (pg_fetch_row($count_result) > 0){?>
            <div class="all-empleados text-center mx-auto rounded-lg pb-2 mt-5 pt-2 ml-3 mr-3 mb-3">
                <h4 class="subtitulo mx-auto">Lista de Empleados</h4>
            </div>
            <table class="table table-hover ">
                <thead class="thead-dark">
                    <tr class="mx-auto text-center">
                        <th style="width: 350px;">Ficha</th>
                        <th style="width: 350px;">Nombre</th>
                        <th style="width: 350px;">Cedula</th>
                        <th style="width: 350px;">Unidad</th>
                        <th style="width: 150px;"><i class="material-icons">edit</i></th>
                        <th style="width: 150px;"><i class="material-icons"><a type="button" class="text-danger" id="delete-btn">delete</a></i></th>
                    </tr>
                </thead>
                <tbody>
                    <?
                        $i = 0;
                        while($row = pg_fetch_row($result)){
                            $i++;
                            ?>
                                <tr class="text-center" id="input-group<?echo $i;?>">
                                    <td>
                                        <p><?echo $row[0];?></p>
                                        <input id="f1-<?echo $i;?>" type="text" placeholder="<?echo $row[0];?>" value="<?echo $row[0];?>" class="form-control d-none" disabled>
                                    </td>
                                    <td>
                                        <p><?echo $row[1];?></p>
                                        <input id="f2-<?echo $i;?>" type="text" placeholder="<?echo $row[1];?>" value="<?echo $row[1];?>" class="form-control d-none" disabled>
                                    </td>
                                    <td>
                                        <p><?echo $row[2];?></p>
                                        <input id="f3-<?echo $i;?>" type="text" placeholder="<?echo $row[2];?>" value="<?echo $row[2];?>" class="form-control d-none">
                                    </td>
                                    <td>
                                        <p><?echo $row[3];?></p>
                                        <input id="f4-<?echo $i;?>" type="text" placeholder="<?echo $row[3];?>" value="<?echo $row[3];?>" class="form-control d-none">
                                    </td>
                                    <td>
                                        <div id="editar<?echo $i;?>"  class="btn-group-toggle" data-toggle="buttons">
                                            <label class="shadow-sm btn btn-secondary">
                                                <input type="checkbox" autocomplete="off" 
                                                onchange="toggleSave(<?echo $i;?>)"> 
                                                    Editar
                                            </label>
                                        </div>
                                        <button id="guardar<?echo $i;?>" 
                                            onclick="updateData(<?echo $i;?>,'#f1-'+'<?echo $i;?>','#f2-'+'<?echo $i;?>','#f3-'+'<?echo $i;?>','#f4-'+'<?echo $i;?>')" 
                                            class="d-none btn btn-success" value="<?echo $i?>" type="button">Guardar
                                            <div class="d-none spinner loadingio-spinner-rolling-bqrptym85uo"><div class="ldio-q0sn9pt0muq">
                                            <div></div>
                                            </div></div>
                                        </button>
                                    </td>
                                    <td class="btn-group-toggle eliminar align-middle">        
                                        <label id="eliminar<?echo $i;?>">
                                            Eliminar <input type="checkbox" autocomplete="off" value="<?echo $i;?>">
                                            <div class="d-none spinner-delete loadingio-spinner-rolling-bqrptym85uo"><div class="ldio-q0sn9pt0muq">
                                            <div></div>
                                            </div></div>
                                        </label>
                                    </td>
                                </tr>
                            <?
                        }
                    ?>
                </tbody>
            </table>
        <?}?>
    </body>
    <script>
        var indexGlob = 0

        function toggleSave(index){
            $('#guardar'+ index ).removeClass('d-none')
            $('#input-group'+index+' .form-control').removeClass('d-none')
            $('#input-group'+index+' p').addClass('d-none')
            $('#editar'+index).addClass('d-none')
        }

        function toggleEdit(index,cedula_update,nombre_update,unidad_update){
            $('#guardar'+ index ).addClass('d-none')
            $('#input-group'+index+' .form-control').addClass('d-none')
            $('#input-group'+index+' p').removeClass('d-none')
            $('#editar'+index).removeClass('d-none')
            $('#guardar'+ index + ' .spinner').addClass('d-none')

            $('#input-group'+index+' p')[1].innerText = nombre_update
            $('#input-group'+index+' p')[2].innerText = cedula_update
            $('#input-group'+index+' p')[3].innerText = unidad_update
        }

        function updateData(index,ficha_update,nombre_update,cedula_update,unidad_update){
                $('#guardar'+ index + ' .spinner').removeClass('d-none')
                var ficha_update = $(ficha_update).val()
                var nombre_update = $(nombre_update).val()
                var cedula_update = $(cedula_update).val()
                var unidad_update = $(unidad_update).val()
                
                setTimeout(function(){
                    $.ajax({
                        url: "update-sede.php",
                        type: "POST",
                        async: true,
                        data: {
                            ficha_responsable: ficha_update,
                            nombre_update: nombre_update,
                            cedula: cedula_update,
                            codigo_unidad: unidad_update
                        },
                        success: function(){
                            toggleEdit(index,cedula_update,nombre_update,unidad_update)
                        }
                    })
                },300)
        }

        $(document).ready(function(){

            $('#delete-btn').click(function(){
                
                var getcheckboxes = $('input:checked').map(function(){
                    var index = $(this).val()
                    indexGlob = index
                    return ficha_empleado = $('#f1-'+index).val()                  
                });
                
                $('#eliminar'+ indexGlob + ' .spinner-delete').removeClass('d-none')
                var codigos = getcheckboxes.get()

                setTimeout(function(){
                    $.ajax({
                        method:'POST',
                        url:'delete-empleado.php',
                        data:{
                            codigos : codigos
                        },
                        async: true,
                        success: function(){
                            $('#input-group'+indexGlob).addClass('d-none')
                            $('#eliminar'+ indexGlob + ' .spinner-delete').addClass('d-none')
                        },
                        error: function(){
                            alert('error')
                        }
                    })
                },500)
            })

            $('#add_empleado_btn').click(addEmpleado)

            function addEmpleado(){
                var cedula = $('#cedula').val()
                var nombre = $('#nombre').val()
                var codigo_unidad = $('#select-unidad').val()
                    $.ajax({
                        method:'POST',
                        url:'add-empleado.php',
                        data: {
                            cedula: cedula, 
                            nombre: nombre,
                            codigo_unidad: codigo_unidad
                            },
                        success: function(){
                            $('#add-empleado-success').removeClass('d-none')
                        },
                        error: function(){
                            $('#add-empleado-error').removeClass('d-none')
                        }
                    })    
            }   

        })
        
    </script>
</html> 

